/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimularRouteImport } from './routes/simular'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ClinicasParceirasRouteImport } from './routes/clinicas-parceiras'
import { Route as CadastroClinicaRouteImport } from './routes/cadastro-clinica'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as ApiGenerateImagePreviewRouteImport } from './routes/api/generate-image-preview'
import { Route as ApiGenerate3dPreviewRouteImport } from './routes/api/generate-3d-preview'
import { Route as ApiGenerate3dModelRouteImport } from './routes/api/generate-3d-model'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated.perfil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedClinicaIndexRouteImport } from './routes/_authenticated.clinica.index'
import { Route as AuthenticatedPacienteDashboardRouteImport } from './routes/_authenticated.paciente.dashboard'
import { Route as AuthenticatedClinicaDashboardRouteImport } from './routes/_authenticated.clinica.dashboard'
import { Route as AuthenticatedAdminSetupRouteImport } from './routes/_authenticated.admin.setup'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimularRoute = SimularRouteImport.update({
  id: '/simular',
  path: '/simular',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicasParceirasRoute = ClinicasParceirasRouteImport.update({
  id: '/clinicas-parceiras',
  path: '/clinicas-parceiras',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroClinicaRoute = CadastroClinicaRouteImport.update({
  id: '/cadastro-clinica',
  path: '/cadastro-clinica',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiGenerateImagePreviewRoute = ApiGenerateImagePreviewRouteImport.update({
  id: '/api/generate-image-preview',
  path: '/api/generate-image-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerate3dPreviewRoute = ApiGenerate3dPreviewRouteImport.update({
  id: '/api/generate-3d-preview',
  path: '/api/generate-3d-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerate3dModelRoute = ApiGenerate3dModelRouteImport.update({
  id: '/api/generate-3d-model',
  path: '/api/generate-3d-model',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClinicaIndexRoute =
  AuthenticatedClinicaIndexRouteImport.update({
    id: '/clinica/',
    path: '/clinica/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacienteDashboardRoute =
  AuthenticatedPacienteDashboardRouteImport.update({
    id: '/paciente/dashboard',
    path: '/paciente/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClinicaDashboardRoute =
  AuthenticatedClinicaDashboardRouteImport.update({
    id: '/clinica/dashboard',
    path: '/clinica/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSetupRoute = AuthenticatedAdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cadastro-clinica': typeof CadastroClinicaRoute
  '/clinicas-parceiras': typeof ClinicasParceirasRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/simular': typeof SimularRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/generate-3d-model': typeof ApiGenerate3dModelRoute
  '/api/generate-3d-preview': typeof ApiGenerate3dPreviewRoute
  '/api/generate-image-preview': typeof ApiGenerateImagePreviewRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/clinica/dashboard': typeof AuthenticatedClinicaDashboardRoute
  '/paciente/dashboard': typeof AuthenticatedPacienteDashboardRoute
  '/clinica/': typeof AuthenticatedClinicaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cadastro-clinica': typeof CadastroClinicaRoute
  '/clinicas-parceiras': typeof ClinicasParceirasRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/simular': typeof SimularRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/generate-3d-model': typeof ApiGenerate3dModelRoute
  '/api/generate-3d-preview': typeof ApiGenerate3dPreviewRoute
  '/api/generate-image-preview': typeof ApiGenerateImagePreviewRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/clinica/dashboard': typeof AuthenticatedClinicaDashboardRoute
  '/paciente/dashboard': typeof AuthenticatedPacienteDashboardRoute
  '/clinica': typeof AuthenticatedClinicaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cadastro-clinica': typeof CadastroClinicaRoute
  '/clinicas-parceiras': typeof ClinicasParceirasRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/simular': typeof SimularRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/api/generate-3d-model': typeof ApiGenerate3dModelRoute
  '/api/generate-3d-preview': typeof ApiGenerate3dPreviewRoute
  '/api/generate-image-preview': typeof ApiGenerateImagePreviewRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/_authenticated/clinica/dashboard': typeof AuthenticatedClinicaDashboardRoute
  '/_authenticated/paciente/dashboard': typeof AuthenticatedPacienteDashboardRoute
  '/_authenticated/clinica/': typeof AuthenticatedClinicaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro-clinica'
    | '/clinicas-parceiras'
    | '/como-funciona'
    | '/simular'
    | '/sitemap.xml'
    | '/dashboard'
    | '/perfil'
    | '/api/generate-3d-model'
    | '/api/generate-3d-preview'
    | '/api/generate-image-preview'
    | '/auth/reset-password'
    | '/admin/dashboard'
    | '/admin/setup'
    | '/clinica/dashboard'
    | '/paciente/dashboard'
    | '/clinica/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro-clinica'
    | '/clinicas-parceiras'
    | '/como-funciona'
    | '/simular'
    | '/sitemap.xml'
    | '/dashboard'
    | '/perfil'
    | '/api/generate-3d-model'
    | '/api/generate-3d-preview'
    | '/api/generate-image-preview'
    | '/auth/reset-password'
    | '/admin/dashboard'
    | '/admin/setup'
    | '/clinica/dashboard'
    | '/paciente/dashboard'
    | '/clinica'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cadastro-clinica'
    | '/clinicas-parceiras'
    | '/como-funciona'
    | '/simular'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/perfil'
    | '/api/generate-3d-model'
    | '/api/generate-3d-preview'
    | '/api/generate-image-preview'
    | '/auth/reset-password'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/setup'
    | '/_authenticated/clinica/dashboard'
    | '/_authenticated/paciente/dashboard'
    | '/_authenticated/clinica/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CadastroClinicaRoute: typeof CadastroClinicaRoute
  ClinicasParceirasRoute: typeof ClinicasParceirasRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  SimularRoute: typeof SimularRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGenerate3dModelRoute: typeof ApiGenerate3dModelRoute
  ApiGenerate3dPreviewRoute: typeof ApiGenerate3dPreviewRoute
  ApiGenerateImagePreviewRoute: typeof ApiGenerateImagePreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simular': {
      id: '/simular'
      path: '/simular'
      fullPath: '/simular'
      preLoaderRoute: typeof SimularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicas-parceiras': {
      id: '/clinicas-parceiras'
      path: '/clinicas-parceiras'
      fullPath: '/clinicas-parceiras'
      preLoaderRoute: typeof ClinicasParceirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-clinica': {
      id: '/cadastro-clinica'
      path: '/cadastro-clinica'
      fullPath: '/cadastro-clinica'
      preLoaderRoute: typeof CadastroClinicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/generate-image-preview': {
      id: '/api/generate-image-preview'
      path: '/api/generate-image-preview'
      fullPath: '/api/generate-image-preview'
      preLoaderRoute: typeof ApiGenerateImagePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-3d-preview': {
      id: '/api/generate-3d-preview'
      path: '/api/generate-3d-preview'
      fullPath: '/api/generate-3d-preview'
      preLoaderRoute: typeof ApiGenerate3dPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-3d-model': {
      id: '/api/generate-3d-model'
      path: '/api/generate-3d-model'
      fullPath: '/api/generate-3d-model'
      preLoaderRoute: typeof ApiGenerate3dModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clinica/': {
      id: '/_authenticated/clinica/'
      path: '/clinica'
      fullPath: '/clinica/'
      preLoaderRoute: typeof AuthenticatedClinicaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/paciente/dashboard': {
      id: '/_authenticated/paciente/dashboard'
      path: '/paciente/dashboard'
      fullPath: '/paciente/dashboard'
      preLoaderRoute: typeof AuthenticatedPacienteDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clinica/dashboard': {
      id: '/_authenticated/clinica/dashboard'
      path: '/clinica/dashboard'
      fullPath: '/clinica/dashboard'
      preLoaderRoute: typeof AuthenticatedClinicaDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/setup': {
      id: '/_authenticated/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AuthenticatedAdminSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminSetupRoute: typeof AuthenticatedAdminSetupRoute
  AuthenticatedClinicaDashboardRoute: typeof AuthenticatedClinicaDashboardRoute
  AuthenticatedPacienteDashboardRoute: typeof AuthenticatedPacienteDashboardRoute
  AuthenticatedClinicaIndexRoute: typeof AuthenticatedClinicaIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminSetupRoute: AuthenticatedAdminSetupRoute,
  AuthenticatedClinicaDashboardRoute: AuthenticatedClinicaDashboardRoute,
  AuthenticatedPacienteDashboardRoute: AuthenticatedPacienteDashboardRoute,
  AuthenticatedClinicaIndexRoute: AuthenticatedClinicaIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CadastroClinicaRoute: CadastroClinicaRoute,
  ClinicasParceirasRoute: ClinicasParceirasRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  SimularRoute: SimularRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGenerate3dModelRoute: ApiGenerate3dModelRoute,
  ApiGenerate3dPreviewRoute: ApiGenerate3dPreviewRoute,
  ApiGenerateImagePreviewRoute: ApiGenerateImagePreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
